### ISSUE TITLE
Move Tables support to a separate package

### ISSUE THREAD

**Issue by trulsf** [hellemo/SparseVariables.jl#20]
Consider moving the implementation of the Tables interface for the variable arrays to a separate package. And also extend support to SparseAxisArray.

**Comment by trulsf** [comment]
Possibly the other way around with a dependency on SparseVariables and JuMP. One option is to only move support for JuMP arrays (DenseAxisArray and SparseAxisArray) to a new package and leave the tables interface for SparseVariableArray (and IndexedVariableArray) as part of SparseVariables.

**Comment by hellemo** [comment]
Looks like JuMP would welcome a PR with Tables support for DenseAxisArray and SparseAxisArray, that would be a good solution, I think. In that case I guess we better keep the Tables support for our own types?

**Comment by trulsf** [comment]
I agree.
